name: Checkov Scan

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
permissions: read-all
jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov
        run: checkov -d .
